/*
* generated by Xtext
*/
package net.sf.hastee.ui.contentassist;

import net.sf.hastee.ui.contentassist.AbstractSTProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class STProposalProvider extends AbstractSTProposalProvider {

}
