/*
 * generated by Xtext
 */
package net.sf.hastee.ui.outline;

import net.sf.hastee.st.NamedObject;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class STOutlineTreeProvider extends DefaultOutlineTreeProvider {

	public void createChildren(IOutlineNode parentNode, EObject modelElement) {
		if (modelElement instanceof NamedObject) {
			super.createChildren(parentNode, modelElement);
		}
	}

}
