/*
 * generated by Xtext
 */
package net.sf.stui.ui.outline;

import java.util.List;

import net.sf.stui.st.NamedTemplate;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class STTransformer extends AbstractDeclarativeSemanticModelTransformer {

	public List<EObject> getChildren(NamedTemplate template) {
		return NO_CHILDREN;
	}

}
