/*
 * generated by Xtext
 */
package net.sf.hastee.ui.labeling;

import net.sf.hastee.st.Group;
import net.sf.hastee.st.NamedObject;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class STLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public STLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	public String image(NamedObject object) {
		return "template.gif";
	}

	public String text(Group group) {
		String[] segments = group.eResource().getURI().segments();
		return segments[segments.length - 1];
	}

}
