/*
 * generated by Xtext
 */
package net.sf.stui.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class STUiModule extends net.sf.stui.ui.AbstractSTUiModule {
	public STUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
